namespace PicView.Avalonia.Win32;

public static class WindowsKeybindings
{
    public const string DefaultKeybindings = """
                                              {
                                                "D": "Next",
                                                "Right": "Next",
                                                "Ctrl+Right": "Last",
                                                "Ctrl+D": "Last",
                                                "Ctrl+Left": "First",
                                                "Ctrl+A": "First",
                                                "Shift+D": "NextFolder",
                                                "Shift+Right": "NextFolder",
                                                "Shift+A": "PrevFolder",
                                                "Shift+Left": "PrevFolder",
                                                "A": "Prev",
                                                "Left": "Prev",
                                                "W": "Up",
                                                "Up": "Up",
                                                "S": "Down",
                                                "Down": "Down",
                                                "PageUp": "ScrollUp",
                                                "PageDown": "ScrollDown",
                                                "Add": "ZoomIn",
                                                "OemPlus": "ZoomIn",
                                                "OemMinus": "ZoomOut",
                                                "Subtract": "ZoomOut",
                                                "Scroll": "ToggleScroll",
                                                "Home": "ScrollToTop",
                                                "End": "ScrollToBottom",
                                                "G": "ToggleGallery",
                                                "F": "Flip",
                                                "Ctrl+Alt+I": "ResizeImage",
                                                "L": "ToggleLooping",
                                                "C": "Crop",
                                                "E": "GalleryClick",
                                                "Enter": "GalleryClick",
                                                "I": "ImageInfoWindow",
                                                "F6": "EffectsWindow",
                                                "F1": "AboutWindow",
                                                "F3": "OpenInExplorer",
                                                "F4": "SettingsWindow",
                                                "F5": "Slideshow",
                                                "F11": "Fullscreen",
                                                "F12": "Fullscreen",
                                                "B": "ChangeBackground",
                                                "Space": "Center",
                                                "K": "KeybindingsWindow",
                                                "Ctrl+O": "Open",
                                                "Ctrl+E": "OpenWith",
                                                "Ctrl+R": "Reload",
                                                "Ctrl+S": "Save",
                                                "Ctrl+Shift+S": "SaveAs",
                                                "F2": "Rename",
                                                "Ctrl+C": "CopyImage",
                                                "Ctrl+Alt+V": "CopyFilePath",
                                                "Ctrl+Shift+C": "CopyFile",
                                                "Ctrl+X": "CutFile",
                                                "Ctrl+V": "Paste",
                                                "Ctrl+P": "Print",
                                                "Alt+Z": "ToggleInterface",
                                                "Delete": "DeleteFile",
                                                "Shift+Delete": "DeleteFilePermanently",
                                                "Ctrl+N": "NewWindow",
                                              }
                                              """;
}
