name: Build PicView Avalonia on macOS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET 9 SDK
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Step 3: Get version from Directory.Build.props using PowerShell
      - name: Get version from Directory.Build.props
        id: get-version
        run: pwsh -File "${{ github.workspace }}/Build/Get-VersionInfo.ps1"

      # Step 4: Build arm64 version using the existing script
      - name: Build arm64 version
        run: |
          pwsh -File "${{ github.workspace }}/Build/Build Avalonia.MacOS arm64.ps1"
        shell: pwsh

      # Step 5: Upload arm64 artifact
      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PicView-v${{steps.get-version.outputs.version}}-macOS-arm64
          path: ${{ github.workspace }}/Build/PicView-v${{steps.get-version.outputs.version}}-macOS-arm64/
          retention-days: 14

      # Step 6: Build x64 version by modifying the platform parameter
      - name: Build x64 version
        run: |
          # Create a copy of the arm64 build script and modify it for x64
          $scriptContent = Get-Content "${{ github.workspace }}/Build/Build Avalonia.MacOS arm64.ps1"
          $scriptContent = $scriptContent -replace '\$platform = "arm64"', '$platform = "x64"'
          $scriptContent | Set-Content "${{ github.workspace }}/Build/Build Avalonia.MacOS x64.ps1"
          
          # Run the x64 build script
          pwsh -File "${{ github.workspace }}/Build/Build Avalonia.MacOS x64.ps1"
        shell: pwsh

      # Step 7: Upload x64 artifact
      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PicView-v${{steps.get-version.outputs.version}}-macOS-x64
          path: ${{ github.workspace }}/Build/PicView-v${{steps.get-version.outputs.version}}-macOS-x64/
          retention-days: 14
